name: Frontend Deploy (Project 2 - Team 2)

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: dev
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      
      - run: npm install
      
      # Set production API URL
      - name: Set production environment
        run: |
          echo "VITE_API_BASE=https://project2.eaglesoftwareteam.com/course-t2" > .env.production
          
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "project2.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/seiv2025/p2/t2"
